const content=document.getElementById('content');
const pages={
home:`<div class="page"><section class="hero"><h2>Welcome to Jaiho Tasdik</h2><p>Your demo gaming hub</p><div class="coins">₹0.37</div><button class="action" onclick="show('games')">Explore Games</button></section><div class="section-title">Featured</div><div class="grid"><div class="card"><h3>🐉 Dragon VS Tiger</h3><p>Demo table game</p><button class="action" onclick="show('dragon')">Play Demo</button></div><div class="card"><h3>🐔 Chicken Road</h3><p>Demo crash-style game</p><button class="action" onclick="show('chicken')">Play Demo</button></div></div><div class="section-title">Quick Access</div><div class="grid"><div class="card" onclick="show('bank')"><h3>🏦 Bank</h3><p>Demo deposit & withdrawal</p></div><div class="card" onclick="show('vip')"><h3>♛ VIP</h3><p>Demo rewards</p></div></div></div>`,
games:`<div class="page"><h2>Games</h2><div class="grid"><div class="card"><h3>🐉 Dragon VS Tiger</h3><p>Cards • Demo only</p><button class="action" onclick="show('dragon')">Open</button></div><div class="card"><h3>🐔 Chicken Road</h3><p>Multiplier • Demo only</p><button class="action" onclick="show('chicken')">Open</button></div></div><div class="note">All game results and balances in this prototype are simulated and have no cash value.</div></div>`,
bank:`<div class="page"><h2>Bank</h2><div class="tabs"><button class="on">Deposit</button><button>Withdraw</button></div><div class="section-title">Demo Balance</div><div class="hero"><div class="big">₹0.37</div><p>Demo wallet</p></div><div class="section-title">Deposit Amount</div><input class="field" value="200" inputmode="numeric"><div class="grid"><button class="card">₹100</button><button class="card">₹200</button><button class="card">₹500</button><button class="card">₹1,000</button></div><button class="action" onclick="alert('Demo only — no payment is processed.')">Deposit Now</button><div class="note warn">No real payment, UPI transaction, or withdrawal is connected.</div></div>`,
transactions:`<div class="page"><h2>My Transactions</h2><div class="tabs"><button class="on">Deposits</button><button>Withdrawals</button><button>Balance</button></div><div class="note">You don't have any demo transactions yet.</div></div>`,
vip:`<div class="page"><h2>VIP</h2><section class="hero"><div class="big">VIP 1</div><p>Demo progress</p><div class="coins">₹200.00</div></section><div class="section-title">VIP Privileges</div><div class="card"><p>◆ Weekly bonus — demo</p><p>◆ Monthly bonus — demo</p><p>◆ Level-up bonus — demo</p><button class="action" onclick="alert('Demo reward only')">Claim Demo Reward</button></div></div>`,
mail:`<div class="page"><h2>Mail</h2><div class="card"><h3>🎁 Welcome to Jaiho Tasdik</h3><p>Thanks for trying the prototype.</p><small>Demo message</small></div></div>`,
dragon:`<div class="page"><h2>Dragon VS Tiger</h2><div class="game"><div class="dragon">🐉</div><div class="tiger">🐯</div><div class="vs">VS</div><div class="cards"><div id="dc" class="playing-card">?</div><div id="tc" class="playing-card">?</div></div><div class="betbar"><button onclick="deal()">Deal Demo Cards</button><span>Demo balance ₹0.37</span></div></div><div class="note">This is a visual demo. No betting or real-money result is recorded.</div></div>`,
chicken:`<div class="page"><h2>Chicken Road</h2><div class="game" style="background:linear-gradient(#777,#444)"><div style="font-size:95px;position:absolute;left:25px;top:130px">🐔</div><div id="mult" style="position:absolute;left:50%;top:120px;transform:translateX(-50%);font-size:42px;font-weight:900;color:#ffd64c">1.00×</div><div class="betbar"><button onclick="runChicken()">Play Demo</button><span>Demo bet ₹100</span></div></div><div class="note">Multiplier is simulated for demonstration and has no cash value.</div></div>`};
function show(p){content.innerHTML=pages[p]||pages.home;document.getElementById('drawer').classList.add('hidden');document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('on',b.dataset.page===p))}
function toggleMenu(){document.getElementById('drawer').classList.toggle('hidden')}
function deal(){const a=[2,4,6,8,10,12,14],s=['♥','♦','♣','♠'];document.getElementById('dc').textContent=a[Math.floor(Math.random()*a.length)]+s[Math.floor(Math.random()*4)];document.getElementById('tc').textContent=a[Math.floor(Math.random()*a.length)]+s[Math.floor(Math.random()*4)]}
function runChicken(){let n=1;const el=document.getElementById('mult');const t=setInterval(()=>{n+=.13;el.textContent=n.toFixed(2)+'×';if(n>=Math.random()*2+1.6){clearInterval(t);el.textContent=n.toFixed(2)+'×';}},180)}
setTimeout(()=>{document.getElementById('splash').classList.add('hidden');document.getElementById('app').classList.remove('hidden');show('home')},2200);
</script>
